bin = "https://raw.githubusercontent.com/extism/extism/main/wasm/code.wasm"

[[test]]
name = "basic"
build = "cd examples/countvowels && tinygo build -o test.wasm -target wasi test.go"
with = "examples/countvowels/test.wasm"
mock_input = { data = "this is my mock input data" }

[[test]]
name = "basic - file input"
build = "cd examples/countvowels && tinygo build -o test.wasm -target wasi test.go"
with = "examples/countvowels/test.wasm"
mock_input = { file = "examples/countvowels/test.go" }
