name: CI
on: [pull_request, workflow_dispatch, push]

jobs:
  test-example:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust:
          - stable
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: '1.21.3'

      - name: Install TinyGo
        uses: acifani/setup-tinygo@v1.1.0
        with:
          tinygo-version: 0.31.2
          binaryen-version: "117"

      - name: Install XTP CLI
        run: curl https://static.dylibso.com/cli/install.sh | sudo sh

      - name: Build Count Vowels Example
        run: |
          cd examples/countvowels && tinygo build -o test.wasm -target wasi test.go

      - name: Test Count Vowels Example
        run: |
          xtp plugin test \
            https://raw.githubusercontent.com/extism/extism/main/wasm/code.wasm \
            --with examples/countvowels/test.wasm

      - name: Build KV Host Function Examples
        run: |
          tinygo build -o host.wasm -target wasi examples/kvhost/main.go
          tinygo build -o plugin.wasm -target wasi examples/kvplugin/main.go
          tinygo build -o test.wasm -target wasi examples/kvtest/main.go
      
      - name: Test KV Host Function Examples
        run: |
          xtp plugin test plugin.wasm --with test.wasm --host host.wasm
